### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by scriptzteam** [vxfemboy/ghostport#2]
Thx for cool piece of code!

https://github.com/vxfemboy/ghostport/blob/bf2dacdaeb138aae349cebe78b60478efd098f75/README.md?plain=1#L55

Should be:
```bash
./target/release/ghostport -s signatures.txt -l 0.0.0.0:8888 -v
```

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
pull request opened, waiting for the merge
